Feature/save model to disk (#156)
* Replaces save_model by joblib.dump in notebooks

All artifacts saved to /tmp/data are persisted. They can be read
later in Deploymnent.ipynb.

* Replaces load_model by joblib.dump in notebooks

All artifacts saved to /tmp/data are persisted. They can be read
in Deploymnent.ipynb.

* Fix issue at Deployment.ipynb for regression models

Fix the error:
ValueError: all the input arrays must have same number of dimensions,
but the array at index 0 has 1 dimension(s) and the array at
index 1 has 0 dimension(s).

* Apply autoformat to notebook files

Uses this plugin for JupyterLab:
https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html#installation-step-1-installing-the-plugin-itself