Fix issue at Deployment.ipynb for regression models
Fix the error:
ValueError: all the input arrays must have same number of dimensions,
but the array at index 0 has 1 dimension(s) and the array at
index 1 has 0 dimension(s).