Fix Variance Threshold and Pre selection - Variance Threshold The features after the pipeline were not being saved according to the changes, making columns with the same name (but different values) and calling the `save_dataset` function of the SDK, generating an exception: `AttributeError: 'Series' object has no attribute 'kind'`.
- Pre selection
The `get_support` method of the` Correlation` class was returning a numpy array with a float dftype, which may cause an exception when trying to delete some index from a list or array using this result: `IndexError: arrays used as indices must be of integer (or boolean) type.