Calls pipeline.transform() before automl.refit()
Refit requires data to be preprocessed, just like automl.fit().
Not doing so causes errors like this:
ValueError: could not convert string to float: '2016-10-08'